version: '3.7'

services:

  frontend:
    build: .
    env_file: .env
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
    depends_on:
      - server
  server:
    build:
      context: ./server
    volumes:
      - .:/src
    ports: 
      - "8000:8000"
    env_file: .env
    stdin_open: true
    command: npm run dev
